### PR TITLE
Several code cleanup issues for .travis/tox/tests code

### PR DESCRIPTION
**Pull request by richm**
use versioned dependencies in req files
clarify valid values for LSR_PUBLISH_COVERAGE
do setup_module_utils per-script with env. vars.
move flake8 args to [flake8] section of tox.ini
drop RUN_FLAKE8_IGNORE in favor of RUN_FLAKE8_EXTRA_ARGS
add license header

### CODE REVIEW

**Comment by richm** [comment]
This now contains all of the code that is merged into network.  Please review.

**Comment by pcahyna** [comment]
I see no problem here - @i386x what do you think? I believe you originally wrote most of this.

**Comment by richm** [comment]
If there are no objections, I'll merge this tomorrow, unless someone else merges it first.

**Comment by tyll** [comment]
I tried to compare the template with the network role. There are still changes that are not synced with the network role in tox.ini, custom.sh and config.sh that are not just customizations for the network role:

```
--- ../../network-lsr/.travis/custom.sh	2020-04-03 17:34:10.981413629 +0200
+++ ./.travis/custom.sh	2020-04-07 22:00:01.652651391 +0200
@@ -1,22 +1,12 @@
 #!/bin/bash
 # SPDX-License-Identifier: MIT
 
-# This script is executed with two arguments passed to it:
-#
-#   $1 - path to environment python (python used inside virtual environment
-#        created by tox)
-#   $2 - path to system python (python 3.x installed on the system)
-
 set -e
 
 ME=$(basename $0)
 SCRIPTDIR=$(readlink -f $(dirname $0))
-TOPDIR=$(readlink -f ${SCRIPTDIR}/..)
 
 . ${SCRIPTDIR}/utils.sh
 . ${SCRIPTDIR}/config.sh
 
 # Write your custom commands here that should be run when `tox -e custom`:
-if [[ -z "${TRAVIS}" ]] || lsr_check_python_version python -eq '3.6'; then
-  (set -x; cd ${TOPDIR}/tests; ${ENVPYTHON} ./ensure_non_running_provider.py)
-fi

--- ../../network-lsr/.travis/config.sh	2020-04-08 09:33:46.896013372 +0200
+++ ./.travis/config.sh	2020-04-08 09:28:37.695991122 +0200
@@ -33,12 +33,17 @@
 #       - RUN_BLACK_INCLUDE
 #       - RUN_BLACK_EXCLUDE
 #       - RUN_BLACK_DISABLED
+#       - RUN_BLACK_EXTRA_ARGS
 #
 #   * .travis/runflake8.sh:
 #
 #       - RUN_FLAKE8_DISABLED
+#       - RUN_FLAKE8_EXTRA_ARGS
+#
+#   * .travis/runsyspycmd.sh:
+#
+#       - function lsr_runsyspycmd_hook
 #
 #   * .travis/runpytest.sh:
 #
 #       - RUN_PYTEST_SETUP_MODULE_UTILS
-LSR_PUBLISH_COVERAGE=normal

--- tox.ini	2020-04-08 09:28:37.698991151 +0200
+++ ../../network-lsr/tox.ini	2020-04-08 09:33:46.898013391 +0200
@@ -160,7 +160,7 @@
 whitelist_externals =
     {[base]whitelist_externals}
 commands =
-    bash {toxinidir}/.travis/runflake8.sh {posargs} .
+    bash {toxinidir}/.travis/runflake8.sh --exclude=.venv,.tox --statistics {posargs} .
 
 [testenv:yamllint]
 deps = yamllint
@@ -255,9 +255,6 @@
 show_source = true
 max-line-length = 88
 ignore = E402,W503
-exclude = .venv,.tox
-statistics = true
-#verbose = 3
 
 [pylint]
 max-line-length = 88
```

Also, there is an `.ansible-lint` file in the template that is not pressent in the network role.

**Comment by tyll** [comment]
The missing changes in the comments for the config files shows another problem with syncing only content instead of changes/commits to the roles. This makes changes like those be missed since the files are not synced anymore in total.

**Comment by richm** [comment]
> The missing changes in the comments for the config files shows another problem with syncing only content instead of changes/commits to the roles. This makes changes like those be missed since the files are not synced anymore in total.

Not sure the best approach for dealing with template files that may have been modified in the repo.  I suppose the script could diff them, and require the user doing the sync to manually merge them.  Ideas welcome.

**Comment by richm** [comment]
> Also, there is an .ansible-lint file in the template that is not pressent in the network role.

https://github.com/linux-system-roles/auto-maintenance/pull/9/files#diff-296847da1bac9d5fceb17648d540cdd3R35

**Comment by richm** [comment]
> > The missing changes in the comments for the config files shows another problem with syncing only content instead of changes/commits to the roles. This makes changes like those be missed since the files are not synced anymore in total.
> 
> Not sure the best approach for dealing with template files that may have been modified in the repo. I suppose the script could diff them, and require the user doing the sync to manually merge them. Ideas welcome.

@tyll the latest commit to https://github.com/linux-system-roles/auto-maintenance/pull/9 adds support for a `--force-copy` option.  Basically, force copying of the files which are normally only copied if they don't exist in the destination, such as `.travis/config.sh`.  The sync script will then issue an error if changes are made:
```
In /home/rmeggins/linux-system-roles/kdump
Not committing - force-copy used and some files were force copied
you will need to manually merge, add, and commit the following files: .gitignore .lgtm.yml .travis/config.sh .travis/custom.sh custom_requirements.txt LICENSE molecule_extra_requirements.txt pylint_extra_requirements.txt pytest_extra_requirements.txt ansible_pytest_extra_requirements.txt .yamllint.yml
```

**Pull request merged**
