### PR TITLE
do not use envpython

### PR DESCRIPTION
**Pull request by richm**
Inside of venvs, just use the `python` command directly - the venv
should have configured `PATH` etc. to use the correct python and
environment.  Use `command -p python` to get the system python.

### CODE REVIEW

**Comment by richm** [comment]
With these fixes, storage passes on all environments - https://github.com/linux-system-roles/storage/pull/75

**Comment by richm** [comment]
Also see https://github.com/linux-system-roles/storage/pull/75/files#diff-2df034cd29949f58ff63f91543d82704R50-R54 for an example of how to skip certain tests on certain environments:
```bash

case $0 in
    *runpytest.sh) if lsr_check_python_version python -lt 2.7 ; then
                       exit 0
                   fi ;;
esac
```

**Comment by pcahyna** [comment]
I am afraid I don't understand this enough

**Comment by richm** [comment]
> I am afraid I don't understand this enough
@i386x and I discussed this over email, copied/pasted here:

> @i386x My initial intention behind `{envpython}` was to work with absolute paths to prevent
> situations like `PATH` poisoning, but now it looks that it is not necessary and
> relying on absolute paths can make problems.
> 
> `$(readlink -f $1)` is here because tox tries to make relative paths from
> absolute ones to keep command line short (`readlink -f` is a workaround
> for `realpath`, since `realpath` is/was not present on Ubuntu). With using just
> `python` instead `{envpython}`, `$(readlink -f $1)` constructs are unnecessary.
> 
> Let use just `python` then, since it looks like that `python` and `{envpython}`
> can refer to different locations (at least for 3.8-dev) and `python` is more
> closer to our needs.

**Comment by richm** [comment]
These changes also work for the network role - see https://lists.fedorahosted.org/archives/list/systemroles@lists.fedorahosted.org/thread/KPA23VKWE7DCFZ7W3TV5SKFQOQEXIWRF/

**Pull request merged**
