### PR TITLE
use tox-lsr 2.2.0

### PR DESCRIPTION
**Pull request by nhosoi**
Upgrade to tox-lsr 2.2.0 to pick up fix for improving collection
testing to get rid of black.

### CODE REVIEW

**Comment by richm** [comment]
I would prefer to leave the template to use `main` to always use the latest - when someone creates a new repo using this template, they can lock down the version of tox-lsr

**Comment by nhosoi** [comment]
> I would prefer to leave the template to use `main` to always use the latest - when someone creates a new repo using this template, they can lock down the version of tox-lsr

I agree. It might not be an issue, but in a role development, the initial template comes from the repo. And the version of tox-lsr is supposed to be sync'ed with the latest released version. How we can make is sure?

I found this in mssql.
```
-  TOX_LSR: "git+https://github.com/linux-system-roles/tox-lsr@main"
+  TOX_LSR: "git+https://github.com/linux-system-roles/tox-lsr@2.2.0"
```

**Comment by richm** [comment]
> > I would prefer to leave the template to use `main` to always use the latest - when someone creates a new repo using this template, they can lock down the version of tox-lsr
> 
> I agree. It might not be an issue, but in a role development, the initial template comes from the repo. And the version of tox-lsr is supposed to be sync'ed with the latest released version. How we can make is sure?
> 
> I found this in mssql.
> 
> ```
> -  TOX_LSR: "git+https://github.com/linux-system-roles/tox-lsr@main"
> +  TOX_LSR: "git+https://github.com/linux-system-roles/tox-lsr@2.2.0"
> ```

I'm not sure I understand the question.  I suppose we could lock down the version of tox-lsr in the template, but then it's just one more thing we have to keep in sync.

**Comment by nhosoi** [comment]
> > > I would prefer to leave the template to use `main` to always use the latest - when someone creates a new repo using this template, they can lock down the version of tox-lsr
> > 
> > 
> > I agree. It might not be an issue, but in a role development, the initial template comes from the repo. And the version of tox-lsr is supposed to be sync'ed with the latest released version. How we can make is sure?
> > I found this in mssql.
> > ```
> > -  TOX_LSR: "git+https://github.com/linux-system-roles/tox-lsr@main"
> > +  TOX_LSR: "git+https://github.com/linux-system-roles/tox-lsr@2.2.0"
> > ```
> 
> I'm not sure I understand the question. I suppose we could lock down the version of tox-lsr in the template, but then it's just one more thing we have to keep in sync.

Well, that's not what we want to do, I'd think. Likely it's something we as a code reviewer check whether it has the expected version. Thanks, @richm. I agree to have `main` in template.

**Pull request closed without merging**
