### PR TITLE
Add default Molecule setup.

### PR DESCRIPTION
**Pull request by vcrhonek**
This setup is used in Molecule-enabled roles at the moment.

Next steps:
- The idea is to synchronize molecule directory from this repo into roles with script similar to:
https://github.com/cloudalchemy/auto-maintenance/blob/master/sync_skeleton.sh
- Docker images can be (re)used from:
https://github.com/paulfantom/dockerfiles
(CentOS6 needs to be added)

### CODE REVIEW

**Comment by vcrhonek** [comment]
> Thank you, LGTM! IMHO it would great to make the template functional so that we can also add a travis config to let it run the molecule config. This would help to ensure that the template configuration is working.

Thanks, good idea. You mean to run 'molecule lint' in travis only? For now I've fixed issues found by yamllint, see PR #3. There are still errors with Ansible lint - '[701] Role info should contain platforms' and bunch of default value in metadata reports similar to '[703] Should change default metadata: author', but that can be 'fixed' with .ansible-lint like:
`---`
`# exclude checks for default metada`
`# please remove this file when you fill meta/main.yml template`
`skip_list:`
`- '701'`
`- '703'`

**Comment by pcahyna** [comment]
The problem with this approach is that if you add molecule or lint configurations specific to the template, then they will not serve themselves as a valid template for the other roles (you don't need to skip those 701 and 703 rules in other roles, and the Molecule sequence will maybe also need to differ.)
@paulfantom any thoughts about this, please?

**Comment by vcrhonek** [comment]
> The problem with this approach is that if you add molecule or lint configurations specific to the template, then they will not serve themselves as a valid template for the other roles (you don't need to skip those 701 and 703 rules in other roles, and the Molecule sequence will maybe also need to differ.)
> @paulfantom any thoughts about this, please?

My understanding (based on https://github.com/linux-system-roles/timesync/pull/34) is that .ansible-lint wouldn't live in molecule directory but in root directory of the role and would be role specific, not synchronized. Yamllint config is a different story.

If you mean molecule sequence in .travis - that should differ in my opinion (it makes no sense to run 'molecule test' in template when there's nothing to test, but it makes sense to run 'molecule lint' to see that template doesn't contain errors of this kind).

But the sequence in molecule/default/molecule.yml wouldn't differ and the whole molecule directory could be synchronized across all roles.

**Comment by pcahyna** [comment]
I think we wanted to share and sync even the Travis configuration (and maybe even Tox, if it can  be made identical).
Even if we don't sync .ansible-lint, it sounds suboptimal to have it in template in a form which is not applicable to the actual roles (that will start their life as copies of the template).

**Comment by tyll** [comment]
> I think we wanted to share and sync even the Travis configuration (and maybe even Tox, if it can be made identical).
> Even if we don't sync .ansible-lint, it sounds suboptimal to have it in template in a form which is not applicable to the actual roles (that will start their life as copies of the template).

The network role is using travis and tox for other tests already. This seems to conflict with make it the same for all roles. Also it should be possible for roles to be more conforming to lint checks if there is no agreement to do the same for all the roles IMHO.

**Comment by paulfantom** [comment]
Basically you shouldn't configure ansible-lint exception in template apart from ones which might be buggy (like comparing to empty string, which is 601 or sth like that). This is to ensure you are following ansible best practices.

I don't see any reason to create any `.ansible-lint` in template repository. If there is any problem reported by ansible-lint, then it should be fixed and in case of 701 and 703 those look trivial.

---

> I think we wanted to share and sync even the Travis configuration 

> The network role is using travis and tox for other tests already.

Sharing same `.travis.yml` across all repos is possible, but then you cannot share same tox. And the other way, sharing tox is possible but not travis. At least that is the case in current state of linux system roles. You need some place to store repo-specific CI configuration.
From my perspective it is usually better to share minimal travis config across all repos and have repo-specific tox. This way you ensure same testing on your local machine and in CI.

---

> it makes no sense to run 'molecule test' in template when there's nothing to test, but it makes sense to run 'molecule lint' to see that template doesn't contain errors of this kind

If there is nothing to test then you have more problems than what should be a sequence. You SHOULD always have something to test. Even simple idempotence run.

And if you care about speed, then pre-bake environment containers instead of rebuilding them all the time with `Dockerfile.j2`.

---

Sorry for going quiet, I had some other tasks which I had to complete.

**Comment by tyll** [comment]
> > The network role is using travis and tox for other tests already.
> 
> Sharing same `.travis.yml` across all repos is possible, but then you cannot share same tox. And the other way, sharing tox is possible but not travis. At least that is the case in current state of linux system roles. You need some place to store repo-specific CI configuration.
> From my perspective it is usually better to share minimal travis config across all repos and have repo-specific tox. This way you ensure same testing on your local machine and in CI.

I would also prefer to be able to customize tox for the same reasons. However, the network role is also running the unit tests against different Python versions with Travis which is also different from the other roles. I am not sure if this can be achieved with just a repo specific tox config.

It is here, if you like to take a look:
https://github.com/linux-system-roles/network

> > it makes no sense to run 'molecule test' in template when there's nothing to test, but it makes sense to run 'molecule lint' to see that template doesn't contain errors of this kind
> 
> If there is nothing to test then you have more problems than what should be a sequence. You SHOULD always have something to test. Even simple idempotence run.
> 
> And if you care about speed, then pre-bake environment containers instead of rebuilding them all the time with `Dockerfile.j2`.

This seems to make sense as well. Just need to ensure that they do not get outdated.

**Comment by paulfantom** [comment]
> running the unit tests against different Python versions with Travis

That's also something that should be tested in all roles and could be customized with tox.

> Just need to ensure that they do not get outdated.

If you create an automated build pipeline in quay (preferable) or in docker hub there is an option to rebuild image when there is a new base image. This is enough to ensure have up-to-date images (considering base image is an official image).

**Pull request merged**
